// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAdminPortal.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BossId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("WorkScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Models.Models.Entities.EmployeeTimeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("WorkDuration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTimeLogs");
                });

            modelBuilder.Entity("Models.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Company Boss - Full Access",
                            Name = "Boss"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "IT Department Boss",
                            Name = "Boss-IT"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Marketing Department Boss",
                            Name = "Boss-Marketing"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Finance Department Boss",
                            Name = "Boss-Finance"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "HR Department Boss",
                            Name = "Boss-HR"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Description = "Sales Department Boss",
                            Name = "Boss-Sales"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Operations Department Boss",
                            Name = "Boss-Operations"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Regular Employee",
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("Models.Models.Entities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLatenessMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinimumWorkMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequiredWorkHours")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            Description = "Standard 8:00-17:00 work schedule",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            MaxLatenessMinutes = 15,
                            MinimumWorkMinutes = 480,
                            Name = "8-17",
                            RequiredWorkHours = 8,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            Description = "Standard 9:00-18:00 work schedule",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsActive = true,
                            MaxLatenessMinutes = 15,
                            MinimumWorkMinutes = 480,
                            Name = "9-18",
                            RequiredWorkHours = 8,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999993"),
                            Description = "Morning shift 9:00-14:00",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            IsActive = true,
                            MaxLatenessMinutes = 10,
                            MinimumWorkMinutes = 300,
                            Name = "9-14",
                            RequiredWorkHours = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999994"),
                            Description = "Afternoon shift 14:00-18:00",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsActive = true,
                            MaxLatenessMinutes = 10,
                            MinimumWorkMinutes = 240,
                            Name = "14-18",
                            RequiredWorkHours = 4,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("EmployeeAdminPortal.Models.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeAdminPortal.Models.Entities.Employee", "Boss")
                        .WithMany("Subordinates")
                        .HasForeignKey("BossId");

                    b.HasOne("Models.Models.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Models.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany("Employees")
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Boss");

                    b.Navigation("Role");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("Models.Models.Entities.EmployeeTimeLog", b =>
                {
                    b.HasOne("EmployeeAdminPortal.Models.Entities.Employee", "Employee")
                        .WithMany("TimeLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Models.Models.Entities.Role", b =>
                {
                    b.HasOne("EmployeeAdminPortal.Models.Entities.Employee", null)
                        .WithMany("ManagedRoles")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("EmployeeAdminPortal.Models.Entities.Employee", b =>
                {
                    b.Navigation("ManagedRoles");

                    b.Navigation("Subordinates");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Models.Models.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Models.Models.Entities.WorkSchedule", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
